language: rust
os:
  - linux
  - windows
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --features enum
  - cargo test --verbose --features enum