[package]
name = "stop-words"
version = "0.1.0"
authors = ["Chris McCOmb <ccmcc2012@gmail.comm"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/cmccomb/vote"
homepage = "https://github.com/cmccomb/vote"
documentation = "https://docs.rs/vote"
license = "MIT OR Apache-2.0"
keywords = ["natural language processing", "stop words"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
